Repository AY2425S2-CS2103T-T13-2/tp, pull requests merged in 2025-04, with the labels that each got.

#164 Branch edit dob
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.High, due:Tuesday

#187 Fix NOK acceptable input bugs
  src/main/java/seedu/address/model/person/NextOfKin.java
Labels: type.Bug, alpha-bug

#191 Implement "assign delete" feature
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/AssignDeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/AssignDeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignDeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AssignDeleteCommandParserTest.java
Labels: due:Tuesday

#195 Edit and Assign nurse feature bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/testutil/CheckTagFromPreviousPerson.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: due:Tuesday

#192 Fix error messages for "view" command
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: due:Tuesday

#193 Branch update sample util data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: alpha-bug

#197 Branch v1.5 edit assign nurse bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
Labels: type.Bug, due:Tuesday

#199 Branch fix address repeated whitespace
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/person/Address.java
Labels: priority.High, due:Tuesday, alpha-bug

#201 fix add command sample format
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High, due:Tuesday

#202 Fix more bugs from alpha test
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: type.Bug, due:Tuesday

#208 Branch developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/images/FindCommandSequenceDiagram.png
Labels: due:Thursday, alpha-bug

#210 Improve code quality for EditCommandParser.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: type.Enhancement, type.Task, due:Wednesday

#212 Upgrade Resultbox GUI
  docs/UserGuide.md
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#206 Branch simple schedule checkup
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
Labels: due:Thursday, alpha-bug

#213 Allow find with prefixes
  src/main/java/seedu/address/logic/commands/FindPatientCommand.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindPatientCommandTest.java
Labels: type.Enhancement

#216 GUI customisation
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/medibook.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Enhancement, priority.High, type.Task, due:Wednesday

#218 Update the user guide
  docs/UserGuide.md
Labels: type.Task

#219 Edit edit and add command UML diagram
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/ListCommandSequenceDiagram.puml
  docs/images/AddCommandSequenceDiagram.png
  docs/images/ListCommandSequenceDiagram.png
Labels: type.Enhancement

#221 Edit GUI and add test cases
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListCommandParserTest.java
  src/test/java/seedu/address/model/person/NextOfKinTest.java
Labels: type.Enhancement

#220 Branch add parameter names
  docs/DeveloperGuide.md
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: due:Thursday, alpha-bug

#222 Add more test cases for code coverage
  src/main/java/seedu/address/model/person/MedicalHistory.java
  src/test/java/seedu/address/model/person/MedicalHistoryTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: type.Enhancement, due:Thursday

#226 Refactor for code quality
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
Labels: type.Enhancement

#229 More code quality fixes
  docs/images/Ui.png
  docs/index.md
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Task

#232 Edit view command to retain UI after other commands
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/person/PersonHasSameNamePredicate.java
Labels: type.Bug, alpha-bug

#236 Fixed a few bugs with Edit feature
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/person/MedicalHistory.java
Labels: due:Thursday

#234 Branch code quality
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/FindNurseCommand.java
  src/main/java/seedu/address/logic/commands/FindPatientCommand.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ScheduleCommandParser.java
  src/main/java/seedu/address/model/checkup/Checkup.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/model/checkup/CheckupTest.java
  src/test/java/seedu/address/model/person/BloodTypeTest.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: priority.High, due:Thursday, alpha-bug

#239 Update User Guide
  docs/UserGuide.md
Labels: due:Thursday

#238 Fix GUI colours
  src/main/resources/view/DarkTheme.css
Labels: due:Thursday

#242 Update the developer guide
  docs/DeveloperGuide.md
Labels: type.Task

#241 Fix more bugs
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: due:Thursday

#320 Limit phone number length
  README.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/MedicalHistory.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/model/person/EmailTest.java
Labels: type.Bug

#322 Allow special character in name
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NextOfKin.java
Labels: Solved (need to update in UG and DG)

#325 Edit user guide and test cases
  docs/UserGuide.md
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/MedicalHistoryTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task

#326 Fix missing NOK error message plus UG upgrade
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
Labels: type.Bug

#331 Edit user guide
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/MedicalHistory.java
Labels: type.Task

#337 Update user guide
  docs/UserGuide.md
  docs/images/AssignScreenshot.png
Labels: type.Task

#338 Branch dr bugs fix
  docs/UserGuide.md
  docs/images/ScheduleCheckupForPatient.png
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindNurseCommandTest.java
  src/test/java/seedu/address/logic/commands/FindPatientCommandTest.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/model/person/DateOfBirthTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.High, due:Monday, alpha-bug

#339 Edit more User Guide stuff
  docs/UserGuide.md
Labels: type.Task

#342 Fix user guide
  docs/UserGuide.md
Labels: type.Task

#345 Branch dr bugs fix
  docs/UserGuide.md
  docs/images/AddPerson.png
  docs/images/ListAllNurseAndPatient.png
  docs/images/ViewMedicalHistory.png
  docs/img.png
  docs/img_1.png
Labels: due:Monday, alpha-bug

#343 Edit user guide
  docs/UserGuide.md
Labels: type.Task

#347 Edit user guide
  docs/UserGuide.md
  docs/images/EditPerson.png
  docs/images/Ui.png
Labels: type.Task

#351 Fix view to edit bug to show all person instead
  docs/UserGuide.md
  docs/UserGuide.pdf
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: alpha-bug

#352 Fix bug and user guide
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Task

#353 Branch dr bugs fix
  docs/DeveloperGuide.md
  docs/diagrams/AddGenericDiagram.puml
  docs/diagrams/AssignGenericDiagram.puml
  docs/diagrams/DeleteGenericDiagram.puml
  docs/diagrams/EditGenericDiagram.puml
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/diagrams/FindGenericDiagram.puml
  docs/diagrams/GenericDiagram.puml
  docs/diagrams/ListGenericDiagram.puml
  docs/diagrams/ScheduleGenericDiagram.puml
  docs/images/AddGenericDiagram.png
  docs/images/AssignGenericDiagram.png
  docs/images/DeleteGenericSequence.png
  docs/images/EditGenericDiagram.png
  docs/images/FindGenericDiagram.png
  docs/images/GenericDiagram.png
  docs/images/ListGenericDiagram.png
  docs/images/ScheduleGenericDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram-Logic.png
  docs/images/UndoSequenceDiagram-Model.png
  src/main/java/seedu/address/logic/commands/ViewCommand.java
Labels: due:Monday, alpha-bug

#354 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddGenericDiagram.puml
  docs/diagrams/FindGenericDiagram.puml
  docs/images/AddGenericDiagram.png
  docs/images/FindGenericDiagram.png
Labels: due:Tuesday, alpha-bug

#357 Fix user guide
  docs/UserGuide.md
Labels: type.Task

#361 Final user guide edit
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/FindPatientOfNurse.png
  docs/images/ScheduleCheckupForPatient.png
Labels: type.Task

#362 Fix user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#363 Fix developer guide
  docs/DeveloperGuide.md
Labels: type.Task

#366 Fix user guide
  docs/UserGuide.md
Labels: type.Task

#371 Fix user guide
  docs/UserGuide.md
Labels: type.Task
